src/doctolib/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
    path('practician/profile/', practician_profile, name='practician_profile'),
    path('patient/profile/', patient_profile, name='patient_profile'),
    path('practician/tickets/', practician_tickets, name='practician_tickets'),
    path('practician/', practician, name='practician'),
    path('appointment/practician/<practician_id>', appointment, name='appointment'),
    path('appointment/practician/<practician_id>/slot/<slot_id>', appointment_confirm, name='appointment_confirm'),
    path('accounts/register/practician', register_practician, name='register_practician'),
    path('practician/slots', practician_slots, name='practician_slots'),
]

src/doctolib/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Slot(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    is_booked = models.BooleanField(default=False)
    user = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='slots')

class Appointment(models.Model):
    slot = models.ForeignKey(Slot, on_delete=models.SET_NULL, null=True)
    user_patient = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='patient')
    user_doctor = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='doctor')
    confirmed = models.BooleanField(default=False)
    done = models.BooleanField(default=False)
    ticket = models.ForeignKey('Ticket', on_delete=models.SET_NULL, null=True)

class Ticket(models.Model):
   user = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
   title = models.CharField(max_length=255)
   user = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='tickets')

   def __str__(self):
       return self.headline

class User(AbstractUser):
    geo_location = models.ForeignKey('GeoLocation', on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.first_name + " " + self.last_name

class GeoLocation(models.Model):
    code_departement = models.CharField(max_length=255)
    nom_departement = models.CharField(max_length=255)
    code_region = models.CharField(max_length=255)
    nom_region = models.CharField(max_length=255)

    def __str__(self):
       return self.nom_departement + " " + self.code_departement + " " + self.nom_region + " " + self.code_region

src/doctolib/forms.py
import unicodedata

from django import forms
from django.contrib.auth import authenticate, get_user_model, password_validation
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Ticket
from .models import GeoLocation
from .models import Slot
from django.forms import TextInput
from django.forms import EmailInput
from django.forms import Select



class UsernameField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize("NFKC", super().to_python(value))

    def widget_attrs(self, widget):
        return {
            **super().widget_attrs(widget),
            "autocapitalize": "none",
            "autocomplete": "username",
        }

class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """

    error_messages = {
        "password_mismatch": _("The two password fields didn’t match."),
    }
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "new-password",
            'class': 'form-control',
            'style': 'max-width: 300px;',
            'placeholder': 'Password',
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={
            "autocomplete": "new-password",
            'class': 'form-control',
            'style': 'max-width: 300px;',
            'placeholder': 'Password confirmation',
        }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = get_user_model()
        fields = ("username",)
        widgets = {
            'username': TextInput(attrs={
                'class': 'form-control',
                'style': 'max-width: 300px;',
                'placeholder': 'Username',
            }),
        }
        field_classes = {"username": UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs[
                "autofocus"
            ] = True

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password2")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("password2", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class PracticianUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username','description','email','geo_location',)
        widgets = {
            'username': TextInput(attrs={
                'class': 'form-control',
                'style': 'max-width: 300px;',
                'placeholder': 'Username',
            }),
            'description': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Description'
            }),
            'email': EmailInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Email'
            }),
            'geo_location': Select(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Geo Location'
            }),
        }

class TicketCreationForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('title',)
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'style': 'max-width: 300px;',
                'placeholder': 'Title',
            }),
        }

class SlotCreationForm(forms.ModelForm):
    class Meta:
        model = Slot
        start_time = forms.DateTimeField
        end_time = forms.DateTimeField
        is_booked = forms.BooleanField()
        fields = ('start_time', 'end_time', 'is_booked')

src/doctolib/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import UserCreationForm, PracticianUpdateForm, TicketCreationForm, SlotCreationForm
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from .models import *
from django.contrib.auth.decorators import login_required

def index(request):
    geoLocations = GeoLocation.objects.all()

    if request.method == 'POST':
        geoLocation = request.POST.get('geoLocation')
        practicians = User.objects.all().filter(geo_location=geoLocation)

        return render(request, 'index.html', {'geoLocations': geoLocations, 'practicians': practicians, 'selectedLocation': geoLocation})

    return render(request, 'index.html', {'geoLocations': geoLocations})

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            group = Group.objects.get(name='patient')
            group.user_set.add(user.id)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def register_practician(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            group = Group.objects.get(name='practician')
            group.user_set.add(user.id)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register_practician.html', {'form': form})

@login_required
def practician_profile(request):
    if request.method == 'POST':
        form = PracticianUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()

    return redirect('practician')

@login_required
def practician_tickets(request):
    if request.method == 'POST':
        form = TicketCreationForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()

    return redirect('practician')

@login_required
def practician(request):
    formUser = PracticianUpdateForm(instance=request.user)
    formTickets = TicketCreationForm()
    tickets = Ticket.objects.filter(user=request.user)

    return render(request, 'practician/profile.html', {'formUser': formUser, 'formTickets': formTickets, 'tickets': tickets})

def appointment(request, practician_id):
    practician = User.objects.get(id=practician_id)
    slots = practician.slots.filter(is_booked=False)

    return render(request, 'appointment/index.html', {'practician': practician, 'slots': slots})

def appointment_confirm(request, practician_id, slot_id):
    if request.method == 'POST':
        ticket = request.POST.get('ticket')

        slot = Slot.objects.get(id=slot_id)
        slot.is_booked = True
        slot.save()

        practician = User.objects.get(id=practician_id)

        appointment = Appointment()
        appointment.user_doctor = practician
        appointment.user_patient = request.user
        appointment.slot = slot
        appointment.ticket = Ticket.objects.get(id=ticket)
        appointment.save()

    return redirect('appointment', practician_id=practician_id)

@login_required
def practician_slots(request):
    if request.method == 'POST':
        form = SlotCreationForm(request.POST)
        if form.is_valid():
            slot = form.save(commit=False)
            slot.user = request.user
            slot.save()
    else:
        form = SlotCreationForm()

    return render(request, 'practician/slots.html', {'form': form})

@login_required
def patient_profile(request):
    appointments = Appointment.objects.all().filter(user_patient=request.user)

    return render(request, 'patient/index.html', {'appointments': appointments})

src/doctolib/templates/practician/Slots.html
{% extends "base.html" %}

{% block content %}

    <div class="w-100 doctolib-bg text-white text-center pb-3">
        <h2 class="font-bold">Add a slot to your availabilities</h2>

        <form class="form-group" method="post" action="{% url 'practician_slots' %}">
            {% csrf_token %}

            <div class="d-flex mx-5">
                <div class="form-control d-flex row">
                    <input class="col" style="border:none" id="id_start_time" type="datetime-local" name="start_time" value="{{ form.start_time.value }}" />
                    <input class="col" style="border:none" id="id_end_time" type="datetime-local" name="end_time" value="{{ form.end_time.value }}" />
                </div>
                <input class="btn btn-warning" type="submit" value="Validate" />
            </div>
        </form>
    </div>

    <br>

    <table class="table table-striped table-hover table-borderless w-75 mt-3">
        <thead>
        <tr>
            <th scope="col">Start time</th>
            <th scope="col">End time</th>
            <th scope="col">Is booked</th>
        </tr>
        </thead>
        <tbody style="vertical-align: middle">
        {% for slot in user.slots.all %}
        <tr>
            <td>{{ slot.start_time }}</td>
            <td>{{ slot.end_time }}</td>
            <td>{{ slot.is_booked }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/doctolib/templates/practician/profile.html
    {% extends "base.html" %}

{% block content %}

<div class="d-flex mt-5 row w-75">
    <div class="col">
        <h1>My Profile</h1>
        <a class="btn btn-primary" href="/practician/slots">My slots</a>

        <br><br>

        <form method="post" action="{% url 'practician_profile' %}">
            {% csrf_token %}
            <div>
                <div class="form-group">
                    {{ formUser.username.label }}
                    {{ formUser.username }}
                    {{ formUser.username.errors }}
                </div>
                <div class="form-group mt-3">
                    {{ formUser.description.label }}
                    {{ formUser.description }}
                    {{ formUser.description.errors }}
                </div>
                <div class="form-group mt-3">
                    {{ formUser.email.label }}
                    {{ formUser.email }}
                    {{ formUser.email.errors }}
                </div>
                <div class="form-group mt-3">
                    {{ formUser.geo_location.label }}
                    {{ formUser.geo_location }}
                    {{ formUser.geo_location.errors }}
                </div>
                <input class="btn btn-primary mt-3" type="submit" value="Validate" />
            </div>
        </form>
    </div>

    <div class="col">
        <h1>Tickets</h1>
        <form method="post" action="{% url 'practician_tickets' %}">
            {% csrf_token %}
            <div>
                <div class="form-group">
                    {{ formTickets.title.label }}
                    {{ formTickets.title }}
                    {{ formTickets.title.errors }}
                </div>
            </div>
            <input class="btn btn-primary mt-3" type="submit" value="Validate" />
        </form>

        <ul class="list-group mt-3" style="max-width: 300px">
            {% for ticket in tickets %}
                <tr>
                    <li class="list-group-item">{{ ticket.title }}</li>
                </tr>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}